export { default as LandingPage } from './LandingPage'
export { default as Login } from './Login'
export { default as Projects } from './Projects'
export { default as Start } from './Start'
export { default as ProjectDetail } from './ProjectDetail'
export { default as Contact } from './Contact'
export { default as NotFoundPage } from './NotFoundPage'
