export { default as Doc } from './Doc'
export { default as LandingPage } from './LandingPage'
export { default as Login } from './Login'
export { default as Projects } from './Projects'
export { default as Start } from './Start'
export { default as ProjectDetail } from './ProjectDetail'
